services:
  db:
    image: postgres:12
    container_name: postgres12
    restart: always
    expose:
      - "5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=cuenca
      - TZ=America/Guayaquil
  spring:
    image: 'jmurillov1/spring:latest'
    container_name: spring
    build:
      context: venta
      dockerfile: Dockerfile
    expose:
      - "8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - logging.level.org.springframework.jdbc.core=DEBUG
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=cuenca
  angular:
    image: 'jmurillov1/angular:latest'
    container_name: angular-service
    build:
      context: vista
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - spring
volumes:
  db_data:
