apiVersion: v1
kind: Service
metadata:
    name: "jmkub-3d32"
    labels:
        app: "jmkub-3d32"
spec:
    type: ClusterIP
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "jmkub-3d32"