on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: dockerimagesjm.azurecr.io
        username: ${{ secrets.acr_dockerimagesjm_username }}
        password: ${{ secrets.acr_dockerimagesjm_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/vista" -f  "vista/Dockerfile" -t dockerimagesjm.azurecr.io/jmkub:${{ github.sha }} --label dockerfile-path=vista/Dockerfile
        docker push dockerimagesjm.azurecr.io/jmkub:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_jmkub_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep default | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace default`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: default
        container-registry-url: dockerimagesjm.azurecr.io
        container-registry-username: ${{ secrets.acr_dockerimagesjm_username }}
        container-registry-password: ${{ secrets.acr_dockerimagesjm_password }}
        secret-name: jmkubdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: default
        manifests: |
          manifests/deployment-1.yml
          manifests/service-1.yml
          manifests/ingress-1.yml
        images: |
          dockerimagesjm.azurecr.io/jmkub:${{ github.sha }}
        imagepullsecrets: |
          jmkubdockerauth
