name: Docker Image CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        context: ./vista
        push: true
        tags: index.docker.io/${{ secrets.DOCKER_HUB_USERNAME }}/spring:${{ github.sha }}
        file: ./Dockerfile
